name: cargo audit

on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.os }}-cargo-audit-v1
      - name: Install cargo-audit
        run: |
          if ! command -v cargo-audit >/dev/null; then
            cargo install cargo-audit
          else
            cargo audit --version  # proves we hit the cache
          fi
      - name: cargo audit
        run: cargo audit --deny warnings
