name: deny

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license-audit:
    name: cargo deny
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: cargo deny licenses
        run: |
          cargo deny --all-features --workspace fetch
          cargo deny --all-features --workspace check
